package View;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Controller.MainFrameController;
import java.awt.*;
import javax.swing.*;
import java.sql.*;
import java.awt.event.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Wind10
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    MainFrameController mainController;
    Connection koneksi;
    private int barispilihan1, barispilihan2, barispilihan3;

    private void kosongkan_form1() {
        txtNIM1.setEditable(true);
        txtNIM1.setText(null);
        txtNama1.setText(null);
        txtJurusan.setText(null);
        jDateDaftar.setCalendar(null);
    }

    private void kosongkan_form2() {
        txtIDBuku1.setEditable(true);
        txtIDBuku1.setText(null);
        txtJudul1.setText(null);
        txtPenerbit.setText(null);
        txtPenulis.setText(null);
        txtTahun.setText(null);
        jDateMasuk.setCalendar(null);
        txtStok.setText(null);
    }

    private void kosongkan_form3() {
        txtIDBuku2.setEditable(true);
        txtIDBuku2.setText(null);
        txtJudul2.setText(null);
        txtNIM2.setEditable(true);
        txtNIM2.setText(null);
        txtNama2.setText(null);
        jDatePinjam.setCalendar(null);
        jDateKembali.setCalendar(null);
    }

    public MainFrame() {
        initComponents();
        mainController = new MainFrameController();
        jTableAnggota.setModel(mainController.SelectAll1());
        jTableBuku.setModel(mainController.SelectAll2());
        jTablePeminjaman.setModel(mainController.SelectAll3());
        jTablePetugas.setModel(mainController.SelectAll4());
        kosongkan_form1();
        kosongkan_form2();
        kosongkan_form3();
    }

    public MainFrame(String username) {
        initComponents();
        mainController = new MainFrameController();
        jTableAnggota.setModel(mainController.SelectAll1());
        jTableBuku.setModel(mainController.SelectAll2());
        jTablePeminjaman.setModel(mainController.SelectAll3());
        jTablePetugas.setModel(mainController.SelectAll4());
        kosongkan_form1();
        kosongkan_form2();
        kosongkan_form3();

        jLabelLogin.setText("Selamat datang " + username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAnggota = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        txtCari1 = new javax.swing.JTextField();
        tbCari1 = new javax.swing.JButton();
        tbTampil1 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtJurusan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNIM1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNama1 = new javax.swing.JTextField();
        jDateDaftar = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        tbSimpan1 = new javax.swing.JButton();
        tbHapus1 = new javax.swing.JButton();
        tbBersih1 = new javax.swing.JButton();
        tbUpdate1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuku = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        txtCari2 = new javax.swing.JTextField();
        tbCari2 = new javax.swing.JButton();
        tbTampil2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtIDBuku1 = new javax.swing.JTextField();
        txtJudul1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        txtPenulis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTahun = new javax.swing.JTextField();
        jDateMasuk = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        tbBersih2 = new javax.swing.JButton();
        tbSimpan2 = new javax.swing.JButton();
        tbUpdate2 = new javax.swing.JButton();
        tbHapus2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePeminjaman = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtCari3 = new javax.swing.JTextField();
        tbCari3 = new javax.swing.JButton();
        tbTampil3 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtIDBuku2 = new javax.swing.JTextField();
        txtJudul2 = new javax.swing.JTextField();
        txtNIM2 = new javax.swing.JTextField();
        txtNama2 = new javax.swing.JTextField();
        jDatePinjam = new com.toedter.calendar.JDateChooser();
        jDateKembali = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tbBersih3 = new javax.swing.JButton();
        tbSimpan3 = new javax.swing.JButton();
        tbUpdate3 = new javax.swing.JButton();
        tbHapus3 = new javax.swing.JButton();
        jButtonLaporan = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        Petugas = new javax.swing.JLabel();
        txtCari4 = new javax.swing.JTextField();
        tbCari4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePetugas = new javax.swing.JTable();
        tbTampil4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Perpustakaan");

        jPanel6.setBackground(new java.awt.Color(135, 205, 214));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistem Informasi Perpustakaan");

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        jLabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLogin.setText("Selamat datang");

        jButtonLogin.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jButtonLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/logout.png"))); // NOI18N
        jButtonLogin.setText("Logout");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButtonLogin)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLogin))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        jTabbedPane1.setBackground(new java.awt.Color(232, 241, 242));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(232, 241, 242));

        jTableAnggota.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnggotaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAnggota);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel18.setText("Cari Mahasiswa :");

        txtCari1.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        txtCari1.setForeground(new java.awt.Color(153, 153, 153));
        txtCari1.setText("masukkan nama atau nim");
        txtCari1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCari1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCari1FocusLost(evt);
            }
        });

        tbCari1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbCari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loupe.png"))); // NOI18N
        tbCari1.setText("Cari");
        tbCari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCari1ActionPerformed(evt);
            }
        });

        tbTampil1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbTampil1.setText("Tampilkan Semua");
        tbTampil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTampil1ActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(232, 241, 242));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Tanggal Daftar :");

        txtJurusan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("NIM :");

        txtNIM1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Nama :");

        txtNama1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jDateDaftar.setToolTipText("");
        jDateDaftar.setDateFormatString("yyyy-MM-dd");
        jDateDaftar.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel5.setText("Jurusan :");

        tbSimpan1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbSimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        tbSimpan1.setText("Tambah");
        tbSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpan1ActionPerformed(evt);
            }
        });

        tbHapus1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        tbHapus1.setText("Hapus");
        tbHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus1ActionPerformed(evt);
            }
        });

        tbBersih1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbBersih1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        tbBersih1.setText("Bersihkan");
        tbBersih1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBersih1ActionPerformed(evt);
            }
        });

        tbUpdate1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbUpdate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/update (1).png"))); // NOI18N
        tbUpdate1.setText("Perbarui");
        tbUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdate1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNIM1)
                            .addComponent(txtNama1)
                            .addComponent(txtJurusan)
                            .addComponent(jDateDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbSimpan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbBersih1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNIM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSimpan1)
                    .addComponent(tbBersih1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbHapus1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbUpdate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbCari1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbTampil1))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbTampil1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbCari1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCari1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        txtCari1.getAccessibleContext().setAccessibleName("");

        jTabbedPane1.addTab("Mahasiswa", jPanel1);

        jPanel2.setBackground(new java.awt.Color(232, 241, 242));

        jTableBuku.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTableBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuku);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel19.setText("Cari Buku :");

        txtCari2.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        txtCari2.setForeground(new java.awt.Color(153, 153, 153));
        txtCari2.setText("masukkan id buku atau judul");
        txtCari2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCari2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCari2FocusLost(evt);
            }
        });

        tbCari2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbCari2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loupe.png"))); // NOI18N
        tbCari2.setText("Cari");
        tbCari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCari2ActionPerformed(evt);
            }
        });

        tbTampil2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbTampil2.setText("Tampilkan Semua");
        tbTampil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTampil2ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(232, 241, 242));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel21.setText("ID Buku :");

        txtIDBuku1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtJudul1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel15.setText("Judul :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel14.setText("Penerbit :");

        txtPenerbit.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtPenulis.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Penulis :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel7.setText("Tahun :");

        txtTahun.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jDateMasuk.setDateFormatString("yyyy-MM-dd");
        jDateMasuk.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jDateMasuk.setMaxSelectableDate(new java.util.Date(253370743286000L));
        jDateMasuk.setMinSelectableDate(new java.util.Date(-62135791114000L));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel8.setText("Tanggal Masuk :");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel9.setText("Stok :");

        txtStok.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        tbBersih2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbBersih2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        tbBersih2.setText("Bersihkan");
        tbBersih2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBersih2ActionPerformed(evt);
            }
        });

        tbSimpan2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbSimpan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        tbSimpan2.setText("Tambah");
        tbSimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpan2ActionPerformed(evt);
            }
        });

        tbUpdate2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbUpdate2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/update (1).png"))); // NOI18N
        tbUpdate2.setText("Perbarui");
        tbUpdate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdate2ActionPerformed(evt);
            }
        });

        tbHapus2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbHapus2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        tbHapus2.setText("Hapus");
        tbHapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPenulis, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTahun, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStok, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbSimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbUpdate2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbBersih2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbHapus2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIDBuku1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtJudul1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPenerbit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDBuku1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSimpan2)
                    .addComponent(tbBersih2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbUpdate2)
                    .addComponent(tbHapus2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCari2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbCari2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbTampil2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tbTampil2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCari2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbCari2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Buku", jPanel2);

        jPanel3.setBackground(new java.awt.Color(232, 241, 242));

        jTablePeminjaman.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTablePeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePeminjamanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTablePeminjaman);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel20.setText("Cari Mahasiswa :");

        txtCari3.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        txtCari3.setForeground(new java.awt.Color(153, 153, 153));
        txtCari3.setText("masukkan nama atau nim");
        txtCari3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCari3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCari3FocusLost(evt);
            }
        });

        tbCari3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbCari3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loupe.png"))); // NOI18N
        tbCari3.setText("Cari");
        tbCari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCari3ActionPerformed(evt);
            }
        });

        tbTampil3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbTampil3.setText("Tampilkan Semua");
        tbTampil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTampil3ActionPerformed(evt);
            }
        });

        jPanel10.setBackground(new java.awt.Color(232, 241, 242));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel16.setText("ID Buku :");

        txtIDBuku2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtJudul2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtNIM2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtNama2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jDatePinjam.setDateFormatString("yyyy-MM-dd");
        jDatePinjam.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jDateKembali.setDateFormatString("yyyy-MM-dd");
        jDateKembali.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel17.setText("Judul :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel10.setText("NIM :");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel11.setText("Nama :");

        jLabel12.setText("Tanggal Pinjam :");

        jLabel13.setText("Tanggal Kembali :");

        tbBersih3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbBersih3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/clear.png"))); // NOI18N
        tbBersih3.setText("Bersihkan");
        tbBersih3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBersih3ActionPerformed(evt);
            }
        });

        tbSimpan3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbSimpan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/add.png"))); // NOI18N
        tbSimpan3.setText("Tambah");
        tbSimpan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbSimpan3ActionPerformed(evt);
            }
        });

        tbUpdate3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbUpdate3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/update (1).png"))); // NOI18N
        tbUpdate3.setText("Perbarui");
        tbUpdate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbUpdate3ActionPerformed(evt);
            }
        });

        tbHapus3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbHapus3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/delete.png"))); // NOI18N
        tbHapus3.setText("Hapus");
        tbHapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbHapus3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJudul2)
                            .addComponent(txtIDBuku2)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbSimpan3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbUpdate3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbHapus3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbBersih3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNIM2)
                            .addComponent(jDateKembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDatePinjam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNama2))))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDBuku2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNIM2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSimpan3)
                    .addComponent(tbBersih3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbUpdate3)
                    .addComponent(tbHapus3))
                .addContainerGap())
        );

        jButtonLaporan.setText("Cetak Laporan");
        jButtonLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonLaporan)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbCari3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbTampil3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbTampil3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCari3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tbCari3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Peminjaman", jPanel3);

        jPanel4.setBackground(new java.awt.Color(232, 241, 242));

        Petugas.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Petugas.setText("Cari Petugas :");

        txtCari4.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        txtCari4.setForeground(new java.awt.Color(153, 153, 153));
        txtCari4.setText("masukkan id petugas");
        txtCari4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCari4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCari4FocusLost(evt);
            }
        });

        tbCari4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbCari4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/loupe.png"))); // NOI18N
        tbCari4.setText("Cari");
        tbCari4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCari4ActionPerformed(evt);
            }
        });

        jTablePetugas.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTablePetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTablePetugas);

        tbTampil4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tbTampil4.setText("Tampilkan Semua");
        tbTampil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbTampil4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Petugas, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCari4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbCari4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tbTampil4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbTampil4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Petugas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbCari4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Petugas", jPanel4);

        jPanel5.setBackground(new java.awt.Color(232, 241, 242));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Sistem layanan terbuka, peminjam bisa mencari buku sendiri/melalui SIM Perpustakaan.\n2. Ketentuan peminjaman buku maksimal 5 eks untuk 10 hari\n3. Prosedur peminjaman buku :\n\ta. Peminjam memilih buku sendiri, kemudian membawanya ke tempat pelayanan.\n\tb. Menunjukkan Kartu Mahasiswa dan menyebutkan nama terangnya.\n\tc. Menuliskan nama, NIM/NIP di slip pengembalian (halaman belakang/depan buku).\n\td. Petugas memproses di komputer dan memberi cap tanggal kembali di slip.\n\te. Menggunakan kartu/namanya sendiri.\n4. Prosedur Pengembalian/Perpanjangan buku bila tidak ada yang memesannya:\n\ta. Menyerahkan buku yang akan dikembalikan/diperpanjang sesuai tempat meminjam.\n\tb. Petugas memproses pengembalian/perpanjangan di komputer & memaraf di slip.\n\tc. Terlambat mengembalikan buku dikenai sanksi denda Rp.800.-/buku/hari.\n5. Perpanjangan melalui SIM Perpustakaan dan sejenisnya, WA/SMS dengan ketentuan:\n\ta. Dilayani untuk hari aktif/non libur, dan bagi yang tidak terlambat tanggal kembalinya.\n\tb. Senin-Jumat: sampai pukul 16.00 WIB, Sabtu: sampai pukul 13.00 WIB.\n\tc. Format Perpanjangan melalui SMS/WA: Nama, NIM, Judul, No.Inventaris, Barcode.\n6. Koleksi yang tidak boleh dipinjam dan hanya boleh dibaca di tempat/difoto kopi adalah :\n\ta. Referensi: kamus, ensiklopedi, atlas, cadangan, skripsi, prosiding, Hasil Penelitian.\n\tb. Terbitan Berkala : jurnal, majalah, koran, buletin.\n\tc. Laporan PKL, askep/askeb, kliping, makalah, dan modul.\n7. KTI, Skripsi, Thesis hanya boleh dibaca di tempat, jika difotokopi aturannya :\n\ta. Mengisi lembar pernyataan yang telah disediakan sebelum memfotokopi.\n\tb. Jumlah yang difotokopi maksimal 3 judul dalam 1 kali fotokopi/print.\n\tc. Langsung mengembalikan pada hari yang sama, terlambat didenda Rp.5.000/judul.\n\td. Mencoret & memaraf daftar yang difotokopi, petugas memaraf bukti pengembalian.\n\te. Koleksi yang sudah dibaca atau difotokopi harus dikembalikan pada tempatnya!\n8. Koleksi AV (CD dan kaset) boleh dipinjam 1 hari dengan mencatat pada buku peminjaman, apabila terlambat mengembalikan dikenai denda Rp.2.000.-/buah/hari.");
        jScrollPane5.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Ketentuan Peminjaman", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbHapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus3ActionPerformed
        // TODO add your handling code here:
        int id_buku = Integer.parseInt(txtIDBuku2.getText());
        String nim = txtNIM2.getText();

        mainController.DeletePeminjaman(id_buku, nim);
        jTablePeminjaman.setModel(mainController.SelectAll3());
        kosongkan_form3();
    }//GEN-LAST:event_tbHapus3ActionPerformed

    private void tbUpdate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdate3ActionPerformed
        // TODO add your handling code here:
        int ID_Buku2 = Integer.parseInt(jTablePeminjaman.getValueAt(barispilihan3, 0).toString());
        String NIM2 = jTablePeminjaman.getValueAt(barispilihan3, 2).toString();
        int id_buku = Integer.parseInt(txtIDBuku2.getText());
        String judul = txtJudul2.getText();
        String nim = txtNIM2.getText();
        String peminjam = txtNama2.getText();
        String tgl_pinjam = ((JTextField) jDatePinjam.getDateEditor().getUiComponent()).getText();
        String tgl_kembali = ((JTextField) jDateKembali.getDateEditor().getUiComponent()).getText();

        mainController.UpdatePeminjaman(id_buku, judul, nim, peminjam, tgl_pinjam, tgl_kembali, ID_Buku2, NIM2);
        jTablePeminjaman.setModel(mainController.SelectAll3());
        kosongkan_form3();
    }//GEN-LAST:event_tbUpdate3ActionPerformed

    private void tbSimpan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpan3ActionPerformed
        // TODO add your handling code here:
        int id_buku = Integer.parseInt(txtIDBuku2.getText());
        String judul = txtJudul2.getText();
        String nim = txtNIM2.getText();
        String peminjam = txtNama2.getText();
        String tgl_pinjam = ((JTextField) jDatePinjam.getDateEditor().getUiComponent()).getText();
        String tgl_kembali = ((JTextField) jDateKembali.getDateEditor().getUiComponent()).getText();

        mainController.InsertPeminjaman(id_buku, judul, nim, peminjam, tgl_pinjam, tgl_kembali);
        jTablePeminjaman.setModel(mainController.SelectAll3());
        kosongkan_form3();

    }//GEN-LAST:event_tbSimpan3ActionPerformed

    private void tbBersih3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBersih3ActionPerformed
        // TODO add your handling code here:
        kosongkan_form3();
    }//GEN-LAST:event_tbBersih3ActionPerformed

    private void tbHapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus2ActionPerformed
        // TODO add your handling code here:
        int id_buku = Integer.parseInt(txtIDBuku1.getText());

        mainController.DeleteBuku(id_buku);
        jTableBuku.setModel(mainController.SelectAll2());
        kosongkan_form2();
    }//GEN-LAST:event_tbHapus2ActionPerformed

    private void tbUpdate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdate2ActionPerformed
        // TODO add your handling code here:
        int ID_Buku = Integer.parseInt(jTableBuku.getValueAt(barispilihan2, 0).toString());
        int id_buku = Integer.parseInt(txtIDBuku1.getText());
        String judul = txtJudul1.getText();
        String penerbit = txtPenerbit.getText();
        String penulis = txtPenulis.getText();
        int tahun = Integer.parseInt(txtTahun.getText());
        String tgl_masuk = ((JTextField) jDateMasuk.getDateEditor().getUiComponent()).getText();
        int stok = Integer.parseInt(txtStok.getText());

        mainController.UpdateBuku(id_buku, judul, penerbit, penulis, tahun, tgl_masuk, stok, ID_Buku);
        jTableBuku.setModel(mainController.SelectAll2());
        kosongkan_form2();
    }//GEN-LAST:event_tbUpdate2ActionPerformed

    private void tbSimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpan2ActionPerformed
        // TODO add your handling code here:
        int id_buku = Integer.parseInt(txtIDBuku1.getText());
        String judul = txtJudul1.getText();
        String penerbit = txtPenerbit.getText();
        String penulis = txtPenulis.getText();
        int tahun = Integer.parseInt(txtTahun.getText());
        String tgl_masuk = ((JTextField) jDateMasuk.getDateEditor().getUiComponent()).getText();
        int stok = Integer.parseInt(txtStok.getText());

        mainController.InsertBuku(id_buku, judul, penerbit, penulis, tahun, tgl_masuk, stok);
        jTableBuku.setModel(mainController.SelectAll2());
        kosongkan_form2();
    }//GEN-LAST:event_tbSimpan2ActionPerformed

    private void tbBersih2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBersih2ActionPerformed
        // TODO add your handling code here:
        kosongkan_form2();
    }//GEN-LAST:event_tbBersih2ActionPerformed

    private void tbHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbHapus1ActionPerformed
        String nim = txtNIM1.getText();

        mainController.DeleteAnggota(nim);
        jTableAnggota.setModel(mainController.SelectAll1());
        kosongkan_form1();
    }//GEN-LAST:event_tbHapus1ActionPerformed

    private void tbUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbUpdate1ActionPerformed
        String NIM = jTableAnggota.getValueAt(barispilihan1, 0).toString();
        String nim = txtNIM1.getText();
        String nama = txtNama1.getText();
        String jurusan = txtJurusan.getText();
        String tgl_daftar = ((JTextField) jDateDaftar.getDateEditor().getUiComponent()).getText();

        mainController.UpdateAnggota(nim, nama, jurusan, tgl_daftar, NIM);
        jTableAnggota.setModel(mainController.SelectAll1());
        kosongkan_form1();
    }//GEN-LAST:event_tbUpdate1ActionPerformed

    private void tbSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbSimpan1ActionPerformed
        String nim = txtNIM1.getText();
        String nama = txtNama1.getText();
        String jurusan = txtJurusan.getText();
        String tgl_daftar = ((JTextField) jDateDaftar.getDateEditor().getUiComponent()).getText();

        mainController.InsertAnggota(nim, nama, jurusan, tgl_daftar);
        jTableAnggota.setModel(mainController.SelectAll1());
        kosongkan_form1();
    }//GEN-LAST:event_tbSimpan1ActionPerformed

    private void tbBersih1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBersih1ActionPerformed
        kosongkan_form1();
    }//GEN-LAST:event_tbBersih1ActionPerformed

    private void tbCari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCari1ActionPerformed
        // TODO add your handling code here:        
        String field = txtCari1.getText();

        jTableAnggota.setModel(mainController.SelectByNimNama(field, field));
        txtCari1.setText(null);
    }//GEN-LAST:event_tbCari1ActionPerformed

    private void tbCari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCari2ActionPerformed
        // TODO add your handling code here:        
        //int field1 = Integer.parseInt(txtCari2.getText());
        String field = txtCari2.getText();

        jTableBuku.setModel(mainController.SelectByIdBukuJudul(field, field));
        txtCari2.setText(null);
    }//GEN-LAST:event_tbCari2ActionPerformed

    private void tbCari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCari3ActionPerformed
        // TODO add your handling code here:       
        String field = txtCari3.getText();

        jTablePeminjaman.setModel(mainController.SelectByNimNama2(field, field));
        txtCari3.setText(null);
    }//GEN-LAST:event_tbCari3ActionPerformed

    private void jTableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnggotaMouseClicked
        // TODO add your handling code here:
        int baris = jTableAnggota.rowAtPoint(evt.getPoint());
        String NIM = jTableAnggota.getValueAt(baris, 0).toString();
        txtNIM1.setText(NIM);
        String Nama = jTableAnggota.getValueAt(baris, 1).toString();
        txtNama1.setText(Nama);
        String Jurusan = jTableAnggota.getValueAt(baris, 2).toString();
        txtJurusan.setText(Jurusan);
        try {
            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTableAnggota.getValueAt(baris, 3));
            jDateDaftar.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        barispilihan1 = baris;
    }//GEN-LAST:event_jTableAnggotaMouseClicked

    private void jTableBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBukuMouseClicked
        // TODO add your handling code here:
        int baris = jTableBuku.rowAtPoint(evt.getPoint());
        String ID_Buku = jTableBuku.getValueAt(baris, 0).toString();
        txtIDBuku1.setText(ID_Buku);
        String Judul = jTableBuku.getValueAt(baris, 1).toString();
        txtJudul1.setText(Judul);
        String Penerbit = jTableBuku.getValueAt(baris, 2).toString();
        txtPenerbit.setText(Penerbit);
        String Penulis = jTableBuku.getValueAt(baris, 3).toString();
        txtPenulis.setText(Penulis);
        String Tahun = jTableBuku.getValueAt(baris, 4).toString();
        txtTahun.setText(Tahun);
        try {
            java.util.Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTableBuku.getValueAt(baris, 5));
            jDateMasuk.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        String Stok = jTableBuku.getValueAt(baris, 6).toString();
        txtStok.setText(Stok);
        barispilihan2 = baris;
    }//GEN-LAST:event_jTableBukuMouseClicked

    private void jTablePeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePeminjamanMouseClicked
        // TODO add your handling code here:
        int baris = jTablePeminjaman.rowAtPoint(evt.getPoint());
        String ID_Buku = jTablePeminjaman.getValueAt(baris, 0).toString();
        txtIDBuku2.setText(ID_Buku);
        String Judul = jTablePeminjaman.getValueAt(baris, 1).toString();
        txtJudul2.setText(Judul);
        String NIM = jTablePeminjaman.getValueAt(baris, 2).toString();
        txtNIM2.setText(NIM);
        String Nama = jTablePeminjaman.getValueAt(baris, 3).toString();
        txtNama2.setText(Nama);
        try {
            java.util.Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTablePeminjaman.getValueAt(baris, 4));
            jDatePinjam.setDate(date1);
            java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse((String) jTablePeminjaman.getValueAt(baris, 5));
            jDateKembali.setDate(date2);
        } catch (ParseException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        barispilihan3 = baris;
    }//GEN-LAST:event_jTablePeminjamanMouseClicked

    private void tbCari4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCari4ActionPerformed
        // TODO add your handling code here:      
        //int field1 = Integer.parseInt(txtCari4.getText());
        String field = txtCari4.getText();

        jTablePetugas.setModel(mainController.SelectByIdPetugasNama(field, field));
        txtCari4.setText(null);
    }//GEN-LAST:event_tbCari4ActionPerformed

    private void tbTampil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTampil3ActionPerformed
        // TODO add your handling code here:
        jTablePeminjaman.setModel(mainController.SelectAll3());
    }//GEN-LAST:event_tbTampil3ActionPerformed

    private void tbTampil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTampil2ActionPerformed
        // TODO add your handling code here:
        jTableBuku.setModel(mainController.SelectAll2());
    }//GEN-LAST:event_tbTampil2ActionPerformed

    private void tbTampil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTampil1ActionPerformed
        // TODO add your handling code here:
        jTableAnggota.setModel(mainController.SelectAll1());
    }//GEN-LAST:event_tbTampil1ActionPerformed

    private void tbTampil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbTampil4ActionPerformed
        // TODO add your handling code here:
        jTablePetugas.setModel(mainController.SelectAll4());
    }//GEN-LAST:event_tbTampil4ActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        // TODO add your handling code here:
        this.dispose();

        LoginForm logform = new LoginForm();
        logform.setVisible(true);
        logform.pack();
        logform.setLocationRelativeTo(null);
        logform.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLaporanActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            koneksi = DriverManager.getConnection(
                    "jdbc:mysql://localhost/perpustakaan",
                    "root", "");
            JasperPrint jp = JasperFillManager.fillReport("C:\\Users\\Wind10\\Documents\\NetBeansProjects\\Simpus\\src\\reportPeminjaman.jasper", null, koneksi);
            JasperViewer.viewReport(jp, false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButtonLaporanActionPerformed

    private void txtCari1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari1FocusGained
        // TODO add your handling code here:
        if (txtCari1.getText().trim().toLowerCase().equals("masukkan nama atau nim")) {
            txtCari1.setText("");
            Font f = new Font("Segoe UI", Font.PLAIN, 13);
            txtCari1.setFont(f);
            txtCari1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCari1FocusGained

    private void txtCari1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari1FocusLost
        // TODO add your handling code here:
        if (txtCari1.getText().trim().equals("") || txtCari1.getText().trim().toLowerCase().equals("masukkan nama atau nim")) {
            txtCari1.setText("masukkan nama atau nim");
            Font f = new Font("Segoe UI", Font.ITALIC, 13);
            txtCari1.setFont(f);
            txtCari1.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCari1FocusLost

    private void txtCari2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari2FocusGained
        // TODO add your handling code here:
        if (txtCari2.getText().trim().toLowerCase().equals("masukkan id buku atau judul")) {
            txtCari2.setText("");
            Font f = new Font("Segoe UI", Font.PLAIN, 13);
            txtCari2.setFont(f);
            txtCari2.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCari2FocusGained

    private void txtCari2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari2FocusLost
        // TODO add your handling code here:
        if (txtCari2.getText().trim().equals("") || txtCari1.getText().trim().toLowerCase().equals("masukkan id buku atau judul")) {
            txtCari2.setText("masukkan id buku atau judul");
            Font f = new Font("Segoe UI", Font.ITALIC, 13);
            txtCari2.setFont(f);
            txtCari2.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCari2FocusLost

    private void txtCari3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari3FocusGained
        // TODO add your handling code here:
        if (txtCari3.getText().trim().toLowerCase().equals("masukkan nama atau nim")) {
            txtCari3.setText("");
            Font f = new Font("Segoe UI", Font.PLAIN, 13);
            txtCari3.setFont(f);
            txtCari3.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCari3FocusGained

    private void txtCari3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari3FocusLost
        // TODO add your handling code here:
        if (txtCari3.getText().trim().equals("") || txtCari1.getText().trim().toLowerCase().equals("masukkan nama atau nim")) {
            txtCari3.setText("masukkan nama atau nim");
            Font f = new Font("Segoe UI", Font.ITALIC, 13);
            txtCari3.setFont(f);
            txtCari3.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCari3FocusLost

    private void txtCari4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari4FocusGained
        // TODO add your handling code here:
        if (txtCari4.getText().trim().toLowerCase().equals("masukkan id petugas")) {
            txtCari4.setText("");
            Font f = new Font("Segoe UI", Font.PLAIN, 13);
            txtCari4.setFont(f);
            txtCari4.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtCari4FocusGained

    private void txtCari4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCari4FocusLost
        // TODO add your handling code here:
        if (txtCari4.getText().trim().equals("") || txtCari1.getText().trim().toLowerCase().equals("masukkan id petugas")) {
            txtCari4.setText("masukkan id petugas");
            Font f = new Font("Segoe UI", Font.ITALIC, 13);
            txtCari4.setFont(f);
            txtCari4.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_txtCari4FocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Petugas;
    private javax.swing.JButton jButtonLaporan;
    private javax.swing.JButton jButtonLogin;
    private com.toedter.calendar.JDateChooser jDateDaftar;
    private com.toedter.calendar.JDateChooser jDateKembali;
    private com.toedter.calendar.JDateChooser jDateMasuk;
    private com.toedter.calendar.JDateChooser jDatePinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableAnggota;
    private javax.swing.JTable jTableBuku;
    private javax.swing.JTable jTablePeminjaman;
    private javax.swing.JTable jTablePetugas;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton tbBersih1;
    private javax.swing.JButton tbBersih2;
    private javax.swing.JButton tbBersih3;
    private javax.swing.JButton tbCari1;
    private javax.swing.JButton tbCari2;
    private javax.swing.JButton tbCari3;
    private javax.swing.JButton tbCari4;
    private javax.swing.JButton tbHapus1;
    private javax.swing.JButton tbHapus2;
    private javax.swing.JButton tbHapus3;
    private javax.swing.JButton tbSimpan1;
    private javax.swing.JButton tbSimpan2;
    private javax.swing.JButton tbSimpan3;
    private javax.swing.JButton tbTampil1;
    private javax.swing.JButton tbTampil2;
    private javax.swing.JButton tbTampil3;
    private javax.swing.JButton tbTampil4;
    private javax.swing.JButton tbUpdate1;
    private javax.swing.JButton tbUpdate2;
    private javax.swing.JButton tbUpdate3;
    private javax.swing.JTextField txtCari1;
    private javax.swing.JTextField txtCari2;
    private javax.swing.JTextField txtCari3;
    private javax.swing.JTextField txtCari4;
    private javax.swing.JTextField txtIDBuku1;
    private javax.swing.JTextField txtIDBuku2;
    private javax.swing.JTextField txtJudul1;
    private javax.swing.JTextField txtJudul2;
    private javax.swing.JTextField txtJurusan;
    private javax.swing.JTextField txtNIM1;
    private javax.swing.JTextField txtNIM2;
    private javax.swing.JTextField txtNama1;
    private javax.swing.JTextField txtNama2;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPenulis;
    private javax.swing.JTextField txtStok;
    private javax.swing.JTextField txtTahun;
    // End of variables declaration//GEN-END:variables
}
